version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthfit
    ports:
      - "3306:3306"
    volumes:
      - ./docker/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
